name: CI Tests

on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "linux-uv"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "~=0.5.9"

    - name: Check lockfile
      run: uv lock --check
        
    - name: Install dependencies
      run: uv sync --frozen --all-extras

    - name: Run ruff
      run: |
        uv run ruff check
        uv run ruff format --check

    - name: Run mypy
      run: uv run mypy  

    - name: Run tests
      run: uv run pytest
